server:
  port: 9999
  servlet:
    context-path: /yyzx
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yyzx
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  minio:
    endpoint: 'http://localhost:9000'
    username: 'adminadmin'
    password: 'adminadmin'
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl