server:
  port: 9999
  servlet:
    context-path: /yyzx
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yyzx
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  minio:
    endpoint: 'http://localhost:9000'
    username: 'adminadmin'
    password: 'adminadmin'
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:1b
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    cn.gugufish.yyzx.controller.ChatController: debug
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl